site_name: FitGreat Authorization
nav:
- 概述: 'summary.md'
- 开发文档: 
    - '准备工作': 'development/prepare.md'
    - '授权码模式': 'development/authorizationcode.md'
    - '密码模式': 'development/resourceownerpassword.md'
    - '客户端模式': 'development/clientcredentials.md'
    - 'Refresh Token': 'development/refreshtoken.md'
    - 'Resource API调用': 'development/apipost.md'
    - 'Introspection': 'development/introspection.md'
    - 'Revocation': 'development/revocation.md'
- 客户端管理: 
    - '登陆': 'client/login.md'
    - '管理客户端': 'client/admin.md'
- 常见问题: 'API/errors.md'

site_description: docs for fitgreat APIs
extra_css:
    - css/extra.css
theme: 
  name: readthedocs
  highlightjs: true
  hljs_languages:
        - yaml
        - rust
markdown_extensions:
    - toc:
        permalink: "#"
plugins:
    - search

